name: Test LR.Tools Setup

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: View available resources
      shell: bash
      run: |
        ls -lha
    # Install LR.Tools
    - name: LogRhythm.Tools - Import Builder
      shell: pwsh
      run: |
        Import-Module ./build/Lrt.Builder.psm1
        New-LrtBuild -Version 1.0.1 -ReleaseTag "Serious Testing" | Publish-LrtBuild -Destination .
    - name: LogRhythm.Tools - Expand Installer
      shell: pwsh
      run: |
        expand-archive ./LogRhythm.Tools-1.0.1.zip
  
    - name: LogRhythm.Tools - Run Installer
      shell: pwsh
      run: |
        ./LogRhythm.Tools-1.0.1/Setup.ps1 -SilentInstall -InstallScope user -TrustSSL yes -LRVersion "7.5.0" -LRAPIKey "55555555555555555555555" -DXIP "127.0.0.1" -LRPMUrl "myhost.com" -LRCaseUrl "myhost.com" -LRAieUrl "myhost.com" -LRSearchUrl "myhost.com" -RecordedFutureAPIKey "55555555555555555555555555555" -UrlScanAPIKey "555555555555555555555555" -ShodanAPIKey "555555555555555555555" -Verbose
    # Import Module
    - name: Import Module - LogRhythm.Tools
      shell: pwsh
      run: |
        Import-Module LogRhythm.Tools